name: Cloud Resume Frontend

on:
  push:
    branches: [main]
    paths: [frontend/**]

env:
  AWS_REGION : 'us-east-1'
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'test' || github.ref == 'refs/heads/production' && 'prod' }}
  CLOUDFRONT_DISTRUBTION: ${{ github.ref == 'refs/heads/main' && secrets.TEST_CLOUDFRONT_DISTRIBUTION_ID || github.ref == 'refs/heads/production' && secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }}
  S3_BUCKET: ${{ github.ref == 'refs/heads/main' && secrets.TEST_AWS_S3_BUCKET || github.ref == 'refs/heads/production' && secrets.PROD_AWS_S3_BUCKET }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: |
          cd frontend && npm ci && npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add profile credentials to ~/.aws/credentials
      run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile iamadmin-general
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile iamadmin-general
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}
    - run: |
        cd frontend && npm ci && npm run build

    - name: Upload to S3 Bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete --follow-symlinks
      env:
        SOURCE_DIR: './frontend/build'
        AWS_REGION: ${{env.AWS_REGION}}
        AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Invalidate CloudFront Cache
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ env.CLOUDFRONT_DISTRUBTION }}
        PATHS: /index.html /static/*
        AWS_REGION: ${{env.AWS_REGION}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
